packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
    dependencies:
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"
  "@vueuse/core@*":
    dependencies:
      vue: "*"
  "@vueuse/integrations@*":
    dependencies:
      vue: "*"
  "@vueuse/shared@*":
    dependencies:
      vue: "*"
